In [1]:
!pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: C:\Users\KIIT\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
#import numpy
#import numpy
import numpy as np
#from numpy import *

In [3]:
a= np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a= np.array([[1,2,3],[4,5,6]], dtype = float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
a.ndim

2

In [6]:
a.shape

(2, 3)

In [7]:
b = a.reshape(3,2)
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [8]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
a= np.arange(2,21,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
a= np.arange(2,21,2).reshape(2,5)
a

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [11]:
arr = np.array([3,6,3,2,3,1,6,5,7,8,7,9])
arr

array([3, 6, 3, 2, 3, 1, 6, 5, 7, 8, 7, 9])

In [12]:
np.unique(arr)

array([1, 2, 3, 5, 6, 7, 8, 9])

In [13]:
np.sort(arr)

array([1, 2, 3, 3, 3, 5, 6, 6, 7, 7, 8, 9])

In [14]:
a= np.array(["Shivani","Annu","Karan"])
np.sort(a)

array(['Annu', 'Karan', 'Shivani'], dtype='<U7')

In [15]:
-np.sort(-arr)

array([9, 8, 7, 7, 6, 6, 5, 3, 3, 3, 2, 1])

In [16]:
a= np.array([1,2,3])
b= np.array([4,5,6])
np.concatenate((a,b), axis=0)

array([1, 2, 3, 4, 5, 6])

In [17]:
a= np.array([[1,2,3],[7,8,9]])
b= np.array([[4,5,6],[3,5,8]])
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6],
       [3, 5, 8]])

In [18]:
np.concatenate((a,b),axis=1)

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 3, 5, 8]])

In [19]:
a= np.array([1,2,3])
b= np.array([4,5,6])

In [20]:
a+b

array([5, 7, 9])

In [21]:
a-b

array([-3, -3, -3])

In [22]:
b-a

array([3, 3, 3])

In [23]:
a*b

array([ 4, 10, 18])

In [24]:
a/b

array([0.25, 0.4 , 0.5 ])

In [25]:
b/a

array([4. , 2.5, 2. ])

In [26]:
a= np.array([[1,2,3],[7,8,9]])
b= np.array([[4,5,6],[3,5,8]])
c=np.concatenate((a,b), axis=0)
c

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6],
       [3, 5, 8]])

In [27]:
c.transpose()

array([[1, 7, 4, 3],
       [2, 8, 5, 5],
       [3, 9, 6, 8]])

In [28]:
np.mean(a)

5.0

In [29]:
np.median(a)

5.0

In [30]:
a= np.array([9,8,9,7,6,5,5,4,3,7,6,2])

In [31]:
import statistics as st
st.mode(a)

9

In [32]:
np.zeros(shape=(3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [33]:
np.ones(shape=(6,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [34]:
# rand, randn, randint

In [35]:
np.random.rand()

0.40740149176712015

In [36]:
np.random.rand(3)

array([0.75447471, 0.06375368, 0.04027477])

In [37]:
np.random.randn()

-1.5674013224022083

In [38]:
np.random.randn(2,3)

array([[-1.13984512, -0.36197043,  0.62764461],
       [ 0.84673153, -0.64441053,  1.3723968 ]])

In [39]:
np.random.randint(5)

1

In [40]:
np.random.randint(-50,-5,5)

array([-24, -12, -35, -31, -20])

In [41]:
np.linspace(0,5,6).reshape(2,3)

array([[0., 1., 2.],
       [3., 4., 5.]])